server:
    port: 7003
spring:
    application:
        name: Eureka Server
        
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/