server:
    port: 7001
spring:
    application:
        name: Eureka Server
        
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/